import type { LifeSimulation, Reminder } from "./types"

export class ExportUtils {
  // Generate PDF report for life simulation (using browser print)
  static async generateSimulationPDF(simulation: LifeSimulation): Promise<void> {
    // Create a printable HTML document
    const printWindow = window.open("", "_blank")
    if (!printWindow) {
      alert("Please allow popups to generate PDF")
      return
    }

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Life Simulation Report - ${simulation.decision}</title>
          <style>
            body {
              font-family: system-ui, -apple-system, sans-serif;
              max-width: 800px;
              margin: 40px auto;
              padding: 20px;
              color: #1a1a1a;
            }
            h1 {
              color: #0ea5e9;
              border-bottom: 3px solid #0ea5e9;
              padding-bottom: 10px;
            }
            h2 {
              color: #334155;
              margin-top: 30px;
            }
            .path {
              background: #f8fafc;
              border-left: 4px solid #0ea5e9;
              padding: 20px;
              margin: 20px 0;
              page-break-inside: avoid;
            }
            .probability {
              font-size: 24px;
              font-weight: bold;
              color: #0ea5e9;
            }
            .impact {
              margin: 10px 0;
              padding: 8px;
              background: white;
              border-radius: 4px;
            }
            .positive { color: #10b981; }
            .negative { color: #ef4444; }
            .neutral { color: #64748b; }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e2e8f0;
              text-align: center;
              color: #64748b;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <h1>Life Echo Simulation Report</h1>
          <p><strong>Decision:</strong> ${simulation.decision}</p>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          
          ${simulation.paths
            .map(
              (path) => `
            <div class="path">
              <h2>${path.title}</h2>
              <p class="probability">Probability: ${path.probability}%</p>
              <p>${path.description}</p>
              
              <h3>Key Impacts:</h3>
              ${path.impacts
                .map(
                  (impact) => `
                <div class="impact">
                  <strong>${impact.dimension}:</strong>
                  <span class="${impact.direction}">${impact.change}</span>
                </div>
              `,
                )
                .join("")}
              
              <p><strong>Grounding:</strong> ${path.grounding}</p>
            </div>
          `,
            )
            .join("")}
          
          <div class="footer">
            <p>Generated by Apex AI Assistant</p>
            <p>This simulation is for informational purposes only and should not be considered as definitive advice.</p>
          </div>
        </body>
      </html>
    `

    printWindow.document.write(html)
    printWindow.document.close()

    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print()
      }, 250)
    }
  }

  // Generate ICS calendar file for reminders
  static generateCalendarExport(reminders: Reminder[]): void {
    const icsContent = this.createICSContent(reminders)
    const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" })
    const url = URL.createObjectURL(blob)

    const link = document.createElement("a")
    link.href = url
    link.download = `apex-reminders-${new Date().toISOString().split("T")[0]}.ics`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  private static createICSContent(reminders: Reminder[]): string {
    const now = new Date()
    const timestamp = now.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z"

    const ics = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Apex AI Assistant//Reminders//EN",
      "CALSCALE:GREGORIAN",
      "METHOD:PUBLISH",
    ]

    reminders.forEach((reminder) => {
      const dueDate = new Date(reminder.dueDate)
      const dueDateStr = dueDate.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z"

      ics.push(
        "BEGIN:VEVENT",
        `UID:${reminder.id}@apexai.app`,
        `DTSTAMP:${timestamp}`,
        `DTSTART:${dueDateStr}`,
        `SUMMARY:${this.escapeICS(reminder.text)}`,
        `STATUS:${reminder.completed ? "COMPLETED" : "CONFIRMED"}`,
        "END:VEVENT",
      )
    })

    ics.push("END:VCALENDAR")
    return ics.join("\r\n")
  }

  private static escapeICS(text: string): string {
    return text.replace(/[,;\\]/g, "\\$&").replace(/\n/g, "\\n")
  }

  // Export knowledge base as markdown
  static exportKnowledgeAsMarkdown(items: Array<{ title: string; content: string; summary?: string }>): void {
    let markdown = `# Apex AI Knowledge Base\n\nExported: ${new Date().toLocaleString()}\n\n---\n\n`

    items.forEach((item) => {
      markdown += `## ${item.title}\n\n`
      markdown += `${item.content}\n\n`
      if (item.summary) {
        markdown += `**AI Summary:** ${item.summary}\n\n`
      }
      markdown += `---\n\n`
    })

    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" })
    const url = URL.createObjectURL(blob)

    const link = document.createElement("a")
    link.href = url
    link.download = `apex-knowledge-${new Date().toISOString().split("T")[0]}.md`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }
}
